import csv

data = [
    # ---- 1. 概述 ----
    {"id": "1", "chapter": "第1章", "section": "1.1 基本描述", "question": "数据融合具体是一个怎样的数据处理过程？", "type": "text_only", "answerability": "answerable", "reference_answer": "数据融合是一个多级、多层面的数据处理过程，主要完成对来自多个信息源的数据进行自动检测、关联、相关及估计的融合处理。", "evidence_span": "数据融合是一个多级、多层面的数据处理过程，主要完成对来自多个信息源的数据进行自动检测、关联、相关及估计的融合处理。", "evidence_page": "11", "difficulty": "Easy", "notes": "基础事实定义抽取"},
    {"id": "2", "chapter": "第1章", "section": "1.1 基本描述", "question": "根据信息层次的不同，目前提到的数据融合主要分为哪三种方式？", "type": "text_only", "answerability": "answerable", "reference_answer": "在数据层（像素级）、特征层和决策层都可以进行数据的融合处理。目前所提到的数据融合也主要包括传感器级、特征级和决策级三种融合方式。", "evidence_span": "在数据层(像素级)、特征层和决策层都可以进行数据的融合处理。目前所提到的数据融合也主要包括传感器级、特征级和决策级三种融合方式", "evidence_page": "11", "difficulty": "Medium", "notes": "需要从段落中归纳三种方式"},
    {"id": "3", "chapter": "第1章", "section": "1.3 应用领域", "question": "多源图像数据所提供的信息与单源相比具有哪三种关键性质？", "type": "text_only", "answerability": "answerable", "reference_answer": "多源图像数据提供的信息具有冗余性、互补性及合作性。", "evidence_span": "与单源图像数据相比，多源图像数据所提供的信息具有冗余性、互补性及合作性。", "evidence_page": "13", "difficulty": "Easy", "notes": "基础罗列"},
    {"id": "4", "chapter": "第1章", "section": "1.3 应用领域", "question": "在多源图像融合中，为什么合理利用冗余信息能够提高识别率？", "type": "cross_segment_reasoning", "answerability": "answerable", "reference_answer": "因为冗余信息是多个传感器提供的对同一目标的感知数据，合理利用它们可以降低误差和减少整体决策的不确定性，进而提高识别的精确度和识别率。", "evidence_span": "合理地利用这些冗余信息，可以降低误差和减少整体决策的不确定性，从而提高识别率和精确度", "evidence_page": "13", "difficulty": "Hard", "notes": "机制原理解释"},
    {"id": "5", "chapter": "第1章", "section": "1.4 现状", "question": "中国是在哪一年完全取代美国成为信息融合领域核心专利占据者的？", "type": "unanswerable", "answerability": "unanswerable", "reference_answer": "抱歉，参考资料中未提供相关信息无法解答。", "evidence_span": "", "evidence_page": "13", "difficulty": "Medium", "notes": "文本提到美国起步早，也提及中国863计划，但未提及专利数取代事实"},
    
    # ---- 2. 数据融合结构 ----
    {"id": "6", "chapter": "第2章", "section": "2.1.1 集中式", "question": "什么是多传感器集中式融合结构？", "type": "text_only", "answerability": "answerable", "reference_answer": "集中式融合是将所有的传感器获得的测量信息，直接输送到中央处理单元进行统一处理。", "evidence_span": "集中式融合是将所有的传感器获得的测量信息，直接输送到中央处理单元进行统一处理。", "evidence_page": "16", "difficulty": "Easy", "notes": "单句事实提取"},
    {"id": "7", "chapter": "第2章", "section": "2.1", "question": "相对于集中式融合，分布式融合结构存在什么优点 and 主要缺点？", "type": "cross_segment_reasoning", "answerability": "answerable", "reference_answer": "分布式融合在处理通信开销和存储要求方面有优势，且系统生存能力强、速度快；主要缺点是它以损失融合中心信息的完整性为代价。", "evidence_span": "与集中式融合相比，分布式融合系统所要求的通信开销小，融合中心计算机所需的存储容量小... 且融合速度快，但这是以损失融合中心信息的完整性为代价的。", "evidence_page": "17", "difficulty": "Medium", "notes": "优缺点的比较归纳"},
    {"id": "8", "chapter": "第2章", "section": "2.1.3 混合式", "question": "混合式融合结构由哪两种融合方式组成？", "type": "text_only", "answerability": "answerable", "reference_answer": "混合式融合中既包含集中式融合，也包含分布式融合。", "evidence_span": "在混合式融合中，既包含集中式融合，也包含分布式融合，它可以由两种融合方式组合而成。", "evidence_page": "18", "difficulty": "Easy", "notes": "简单成分识别"},
    {"id": "9", "chapter": "第2章", "section": "2.3.1 卡尔曼滤波", "question": "卡尔曼滤波器是如何获得系统的状态估计值的？", "type": "cross_segment_reasoning", "answerability": "answerable", "reference_answer": "卡尔曼滤波器是由一组数学方程所构成，它以最小化均方根的方式来获得系统的状态估计值。", "evidence_span": "卡尔曼滤波器是由一组数学方程所构成，它以最小化均方根的方式。来获得系统的状态估计值。", "evidence_page": "20", "difficulty": "Medium", "notes": "机制原理解释"},
    {"id": "10", "chapter": "第2章", "section": "2.3.2 序贯算法", "question": "在序贯式卡尔曼滤波中对雷达和红外传感器进行融合时，为什么需要在红外数据中补充雷达的径向距离？", "type": "cross_segment_reasoning", "answerability": "answerable", "reference_answer": "因为红外传感器获得的数据是二维的（仅有高低角和方位角），为了与雷达测量数据保持一致以供融合，需要用雷达的径向距离作为红外观测的补充。", "evidence_span": "由于红外传感器获得的数据是二维的，仅有高低角和方位角，为了与雷达测量数据保持一致，在红外测量数据中，需要将雷达数据中的径向距离作为红外观测数据的补充", "evidence_page": "22", "difficulty": "Hard", "notes": "工程中数据对齐的深层原因揭示"},
    {"id": "11", "chapter": "第2章", "section": "2.3.1 卡尔曼滤波", "question": "卡尔曼滤波器能否在零下50度的恶劣极地环境下正常处理雷达信号而不失真？", "type": "unanswerable", "answerability": "unanswerable", "reference_answer": "抱歉，参考资料中未提供相关信息无法解答。", "evidence_span": "", "evidence_page": "20", "difficulty": "Hard", "notes": "植入环境要素混淆概念"},

    # ---- 3. 贝叶斯推理 ----
    {"id": "12", "chapter": "第3章", "section": "3.1 贝叶斯法则", "question": "贝叶斯推理方法在数据融合技术中属于哪一类算法，其理论基础是什么？", "type": "text_only", "answerability": "answerable", "reference_answer": "它属于统计融合算法，其理论基础是贝叶斯法则。", "evidence_span": "贝叶斯推理方法是一种统计方法，在数据融合中属于统计融合算法，其理论基础是贝叶斯法则。", "evidence_page": "24", "difficulty": "Easy", "notes": "单句基础回答"},
    {"id": "13", "chapter": "第3章", "section": "3.1 贝叶斯法则", "question": "在给定的矿物探测实例中，结合地下探测雷达(GPR)和金属探测器(MD)融合的核心原理是什么？", "type": "cross_segment_reasoning", "answerability": "answerable", "reference_answer": "核心原理是使用贝叶斯法则结合两者的后验概率公式计算，由于MD和GPR响应不同的独立物理现象产生的数据相互独立，可以用联合概率公式求出被测物体属于某类的后验概率以提高检测率。", "evidence_span": "可以用贝叶斯推理来计算被测物体是属于哪类的后验概率...因为两类传感器产生的信号相互独立，所以传感器联合报表概率为...", "evidence_page": "26", "difficulty": "Hard", "notes": "跨段落结合公式原理的应用解释"},
    {"id": "14", "chapter": "第3章", "section": "3.2.1 贝叶斯网络", "question": "在贝叶斯网络图结构中，根节点和叶节点的区别是什么？", "type": "cross_segment_reasoning", "answerability": "answerable", "reference_answer": "根节点是只有子节点而无父节点的节点；而叶节点则正好相反，它只有父节点而无子节点。", "evidence_span": "这种只有子节点而无父节点的节点也被称为根节点。相反，节点D(湿草地)及节点E(湿滑路面)则只有父节点而无子节点，这样的节点被称叶节点。", "evidence_page": "28", "difficulty": "Medium", "notes": "概念区分"},
    {"id": "15", "chapter": "第3章", "section": "3.2.2 有向分离", "question": "在贝叶斯网络中，有向分离的三种特殊节点连接情况分别叫什么？", "type": "text_only", "answerability": "answerable", "reference_answer": "三种特殊的连接方式是第一类顺序连接（头对尾）、第二类发散连接（尾对尾）和第三类收敛连接（头对头）。", "evidence_span": "第一类是顺序连接...第二类是发散连接...第三类是收敛连接...", "evidence_page": "29", "difficulty": "Medium", "notes": "列举题"},
    {"id": "16", "chapter": "第3章", "section": "3.2.3 结构学习", "question": "基于数据学习贝叶斯网络结构时可能遇到什么问题？", "type": "cross_segment_reasoning", "answerability": "answerable", "reference_answer": "由于贝叶斯网络结构空间的大小会随着节点的数目以及节点的状态数呈现指数级别增长，这会使得结构学习成为一个NP问题，带来极大的计算和搜索复杂度。", "evidence_span": "由于贝叶斯网络结构空间的大小会随看节点的数目以及节点的状态数呈现指数级别增长，使得结构学习成为一个NP问题。", "evidence_page": "31", "difficulty": "Hard", "notes": "探讨计算复杂度原因"},
    {"id": "17", "chapter": "第3章", "section": "3.2.3 结构学习", "question": "基于约束的贝叶斯结构学习方法有容易被忽略的什么弱点？", "type": "cross_segment_reasoning", "answerability": "answerable", "reference_answer": "它的缺点是当训练数据量不足或存在噪声时，常常会出现精度较低的现象，结果将会与实际偏差较大。", "evidence_span": "但会有精度较低的现象出现，一旦数据不足或存在噪声时，结果将会与实际偏差较大。", "evidence_page": "32", "difficulty": "Medium", "notes": "优缺点分析"},
    {"id": "18", "chapter": "第3章", "section": "3.2 贝叶斯网络", "question": "贝叶斯网络中马尔可夫条件的底层量子纠缠机制是什么？", "type": "unanswerable", "answerability": "unanswerable", "reference_answer": "抱歉，参考资料中未提供相关信息无法解答。", "evidence_span": "", "evidence_page": "27", "difficulty": "Hard", "notes": "诱惑性专业名词嫁接"},

    # ---- 4. 证据理论 (DS) 及其他泛化问题 ----
    {"id": "19", "chapter": "第4章", "section": "4.1 DS", "question": "D-S证据理论中，Dempster合成规则在什么情况下不适用或受到局限？", "type": "cross_segment_reasoning", "answerability": "answerable", "reference_answer": "D-S理论要求证据必须是独立的（该条件在实际中不易满足），而且当证据之间高度冲突时合成规则的合理性存在争议，此外还有潜在的指数爆炸计算问题。", "evidence_span": "其局限性在于要求证据必须是独立的...合成规则的合理性存在争议，且在计算上存在潜在的指数爆炸问题。", "evidence_page": "36", "difficulty": "Hard", "notes": "提取限制条件"},
    {"id": "20", "chapter": "第4章", "section": "4.2 DS", "question": "在D-S证据理论中，基本概率赋值(BPA)是如何影响不确定区间的？", "type": "cross_segment_reasoning", "answerability": "answerable", "reference_answer": "BPA帮助我们计算命题的信任度(Bel)和似然度(Pl)，而[Bel, Pl]就构成了不确定区间。如果不确定区间很大，说明对该命题所掌握的有效证据很不充分。", "evidence_span": "它帮助构成了不确定区间。如果不确定区间很大，说明掌握的有效证据很不充分。", "evidence_page": "38", "difficulty": "Medium", "notes": "逻辑解释"},
    {"id": "21", "chapter": "第4章", "section": "4.3 证据与贝叶斯", "question": "证据理论与贝叶斯理论在处理不确定性时最核心的差异是什么？", "type": "cross_segment_reasoning", "answerability": "answerable", "reference_answer": "贝叶斯理论需要已知完整的先验概率，且假设状态概率必须和为1；而D-S证据理论不需要先验概率，允许“不知道”这种信念的存在，能更好地处理不确定和匮乏信息。", "evidence_span": "贝叶斯理论需要已知完整的先验概率...而D-S证据理论不需要先验概率，允许不知道这种信念的存在...", "evidence_page": "41", "difficulty": "Hard", "notes": "两大经典算法差异"},
    {"id": "22", "chapter": "第4章", "section": "4.4 图像融合应用", "question": "以学生端坐或左顾右盼为例，DS证据理论是如何结合摄像头的多个特征来做决策的？", "type": "cross_segment_reasoning", "answerability": "answerable", "reference_answer": "通过从图像中提取人脸偏转角度、身体晃动幅度等独立特征作为不同“证据源”，给各状态赋予基本概率后利用Dempster规则进行正交合成计算最大可能性。", "evidence_span": "提取人脸偏转角度、身体晃动幅度等独立特征作为不同证据源，给各状态赋予基本概率后利用Dempster规则进行合成计算。", "evidence_page": "44", "difficulty": "Medium", "notes": "场景模拟"},
    {"id": "23", "chapter": "第4章", "section": "4.4", "question": "有没有明确的证据理论实验数据表明学生在吃零食时BPA分配极度失衡？", "type": "unanswerable", "answerability": "unanswerable", "reference_answer": "抱歉，参考资料中未提供相关信息无法解答。", "evidence_span": "", "evidence_page": "49", "difficulty": "Medium", "notes": "不存在该实验"},
    {"id": "24", "chapter": "第5章", "section": "5.2 模糊逻辑", "question": "模糊计算原理中的核心元件是什么，它主要解决什么系统问题？", "type": "text_only", "answerability": "answerable", "reference_answer": "核心是模糊控制器，它主要用于解决那些由于非线性、大时滞等因素难以建立精确数学模型的复杂控制对象问题。", "evidence_span": "模糊计算原理核心是模糊控制器，主要用于解决难以建立精确数学模型的复杂控制对象问题。", "evidence_page": "60", "difficulty": "Easy", "notes": "事实归纳"},
    {"id": "25", "chapter": "第5章", "section": "5.3 球杆系统", "question": "在球杆系统模糊控制器中，为什么需要对传统PID进行模糊推论化改进？", "type": "cross_segment_reasoning", "answerability": "answerable", "reference_answer": "因为小球的动力学系统本身具有强烈的非线性和欠驱动性特征，传统固定系数的PID在应对外部干扰和初始大偏差时容易震荡，模糊推论能自适应调节改善超调量。", "evidence_span": "球杆系统本身具有强烈的非线性机制...容易震荡，模糊推论能自适应调节改善超调量。", "evidence_page": "66", "difficulty": "Medium", "notes": "控制逻辑分析"},
    {"id": "26", "chapter": "第6章", "section": "6.2 BP神网", "question": "采用BP神经网络进行多传感器数据融合时算法具有什么致命的收敛缺陷？", "type": "cross_segment_reasoning", "answerability": "answerable", "reference_answer": "BP神经网络的核心是使用梯度下降的反向传播，因此它极其容易陷入局部极小值而非全局最优，而且当学习速率选取不当时会导致网络震荡难以收敛。", "evidence_span": "BP神经网络极其容易陷入局部极小值而非全局最优，而且当学习速率选取不当时会导致网络震荡难以收敛。", "evidence_page": "78", "difficulty": "Hard", "notes": "算法缺陷深度分析"},
    {"id": "27", "chapter": "第6章", "section": "6.4 Hopfield", "question": "Hopfield神经网络相较于前馈网络，主要被应用于解决什么领域的融合难题？", "type": "text_only", "answerability": "answerable", "reference_answer": "它主要被应用于解决复杂的优化问题（如TSP路径优化）以及联想记忆修复等领域。", "evidence_span": "主要被应用于解决复杂的优化问题与联想记忆修复等领域。", "evidence_page": "82", "difficulty": "Easy", "notes": "应用领域提取"},
    {"id": "28", "chapter": "第7章", "section": "7.2 遗传算法", "question": "遗传算法中的交叉和变异操作对全局寻优各自起到了什么宏观作用？", "type": "cross_segment_reasoning", "answerability": "answerable", "reference_answer": "交叉操作通过基因重组产生具有优秀性状的下一代；而变异操作则维持了种群的多样性，宏观上有效防止了算法过早地收敛于局部极值点。", "evidence_span": "交叉操作通过基因重组产生优秀性状...变异操作则维持了种群的多样性，宏观上有效防止了算法过早地收敛。", "evidence_page": "88", "difficulty": "Medium", "notes": "机制比对"},
    {"id": "29", "chapter": "第7章", "section": "7.3.3 遗传航迹关联", "question": "遗传算法在何种航天器的曲率折叠跃迁轨道融合计算上被证明无效？", "type": "unanswerable", "answerability": "unanswerable", "reference_answer": "抱歉，参考资料中未提供相关信息无法解答。", "evidence_span": "", "evidence_page": "94", "difficulty": "Hard", "notes": "生造概念混淆"},
    {"id": "30", "chapter": "第8章", "section": "8.1 粒子群", "question": "如果粒子群算法中的局部最优解(pbest)与多模态目标关联算法冲突，应如何强行合并？", "type": "unanswerable", "answerability": "unanswerable", "reference_answer": "抱歉，参考资料中未提供相关信息无法解答。", "evidence_span": "", "evidence_page": "100", "difficulty": "Hard", "notes": "专业误导题拒答考察"},
    
    # ---- 5. 核心公式提取与符号推敲 (面向理工科抗幻觉体系) ----
    {"id": "31", "chapter": "第2章", "section": "2.3.1 卡尔曼滤波", "question": "卡尔曼滤波器的状态更新方程（又称为状态预测方程）完整的数学表达式是什么？", "type": "formula_dependent", "answerability": "answerable", "reference_answer": "系统的状态更新方程表示为：X_k = Φ_{k,k-1} X_{k-1} + W_{k-1}，其中 Φ 为状态转移矩阵，W 为带有协方差矩阵的系统噪声序列。", "evidence_span": "可以表示为 X_k = Φ_k,k-1 X_k-1 + W_k-1 ...", "evidence_page": "20", "difficulty": "Hard", "notes": "测试大模型对带有下标变量的控制公式重建能力"},
    
    {"id": "32", "chapter": "第2章", "section": "2.3.1 卡尔曼滤波", "question": "在卡尔曼滤波的五大核心方程里，增益矩阵表达式中用来代表量测误差协方差矩阵的是由哪个大写字母构成的数学符号？", "type": "formula_dependent", "answerability": "answerable", "reference_answer": "该大写字母符号是 R。表示测量噪声向量 V_k 的协方差矩阵。", "evidence_span": "V_k 是方差为 R 的零均值白噪声，代表量测噪声", "evidence_page": "20", "difficulty": "Medium", "notes": "考验对孤立代数符号及其物理意义的一对一辨析能力"},
    
    {"id": "33", "chapter": "第4章", "section": "4.1 DS", "question": "Dempster合成规则（D-S证据正交和规则）公式分母中的常数项 1-K 里，K 代表什么物理意义或冲突描述？", "type": "formula_dependent", "answerability": "answerable", "reference_answer": "这里的 K 是衡量两个不同传感器或来源证据之间冲突程度大小的系数，K 越大表明证据之间碰撞越尖锐，如果 K 趋近于 1 会使得分母趋向 0，发生悖论。", "evidence_span": "其中 K 反映了不同证据之间的冲突程度大小，当 K 非常大时说明证据极不兼容...", "evidence_page": "36", "difficulty": "Hard", "notes": "针对公式分母中的微小参数做专门的知识解释考察"},
    
    {"id": "34", "chapter": "第4章", "section": "4.2 DS", "question": "D-S理论中用于表示基本概率赋值向目标全集映射的规范化数学形式是怎样的？", "type": "formula_dependent", "answerability": "answerable", "reference_answer": "基本概率赋值的要求是 m(空集)=0 且集合中所有子集A的m(A)求和必须等于1。即 Σ m(A) = 1 (A ⊆ Θ) 。", "evidence_span": "满足两条规则，第一是空集的赋值为0，第二是对全集下的元素求和等于1...", "evidence_page": "37", "difficulty": "Medium", "notes": "测试模型对统计学大范围求和条件的严密捕捉率"},
    
    {"id": "35", "chapter": "第3章", "section": "3.1 贝叶斯法则", "question": "在利用贝叶斯法则进行多传感器序列数据连续更新（如递归滤波）时，它的递推数学形态是否包含了微积分操作？", "type": "formula_dependent", "answerability": "unanswerable", "reference_answer": "抱歉，参考资料中并未提供将连续微积分符号加入联合概率特征报表数据的信息，故无法回答其公式形态。", "evidence_span": "", "evidence_page": "24", "difficulty": "Hard", "notes": "引入伪造的数学操作术语进行强诱骗陷阱"}
]

csv_file = "data/benchmark.csv"
fieldnames = ["id", "chapter", "section", "question", "type", "answerability", "reference_answer", "evidence_span", "evidence_page", "difficulty", "notes"]

with open(csv_file, mode="w", newline="", encoding="utf-8-sig") as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    for row in data:
        writer.writerow(row)

print(f"Successfully generated {len(data)} strictly formatted benchmark records!")
